"""Generate jacoco_coverage_extraction.ipynb."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
METRIC_ROOT = ROOT.parent
NOTEBOOK = METRIC_ROOT / "jacoco_coverage_extraction.ipynb"
UTILS = (ROOT / "_jacoco_notebook_utils.py").read_text(encoding="utf-8")


def md(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": [line + "\n" for line in source.split("\n")]}


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in source.split("\n")],
    }


cells = [
    md(
        "# JaCoCo Code Coverage — Raw Output Extraction (Java)\n\n"
        "This notebook performs **end-to-end execution of JaCoCo** against a Java repository and captures "
        "the **complete raw build/test output** plus the official JaCoCo report artifacts.\n\n"
        "**Default repository:** "
        "[visvantha-testable/java-tool-testing-jacoco]"
        "(https://github.com/visvantha-testable/java-tool-testing-jacoco)\n\n"
        "> **Note:** Metrics are parsed only from official JaCoCo `jacoco.xml` and `jacoco.csv` reports. "
        "Copied XML, CSV, HTML, and `.exec` files are preserved exactly as generated by JaCoCo."
    ),
    md(
        "## Section 1 — Install Dependencies\n\n"
        "Install Java, Maven/Gradle prerequisites, and Python packages. "
        "Colab/Linux cells use `apt-get`; Windows uses bundled or system Java/Maven when available."
    ),
    code(
        "import platform\n"
        "import shutil\n"
        "import subprocess\n"
        "import sys\n\n"
        "IS_COLAB = 'google.colab' in sys.modules\n"
        "IS_LINUX = platform.system() == 'Linux'\n\n"
        "if IS_COLAB or IS_LINUX:\n"
        "    !apt-get update -qq\n"
        "    !apt-get install -y openjdk-17-jdk maven\n\n"
        "!pip install -q pandas gitpython notebook jupyter\n\n"
        "print('Java:')\n"
        "subprocess.run(['java', '-version'], check=False)\n"
        "if shutil.which('mvn'):\n"
        "    print('\\nMaven:')\n"
        "    subprocess.run(['mvn', '-version'], check=False)\n"
        "if shutil.which('gradle'):\n"
        "    print('\\nGradle:')\n"
        "    subprocess.run(['gradle', '-version'], check=False)"
    ),
    md("## Section 2 — Configuration"),
    code(
        "USE_GIT_REPO = True\n\n"
        "REPO_URL = 'https://github.com/visvantha-testable/java-tool-testing-jacoco.git'\n\n"
        "LOCAL_REPO = './workspace/java-tool-testing-jacoco'\n\n"
        "WORKSPACE_DIR = './workspace'\n"
        "OUTPUT_DIR = './outputs'\n"
        "IF_CLONE_EXISTS = 'reuse'\n"
        "CLONE_DEPTH = 1\n"
        "RAW_OUTPUT_PREVIEW_LINES = 150\n\n"
        "# Local mode example:\n"
        "# USE_GIT_REPO = False\n"
        "# LOCAL_REPO = './workspace/java-tool-testing-jacoco'\n\n"
        "# Colab example:\n"
        "# USE_GIT_REPO = False\n"
        "# LOCAL_REPO = '/content/java-tool-testing-jacoco'"
    ),
    md("## Section 3 — Imports and Utility Functions"),
    code("from pathlib import Path\n\nfrom IPython.display import display\n\n" + UTILS.strip()),
    md("## Section 4 — Repository Information"),
    code(
        "OUTPUT_PATH = Path(OUTPUT_DIR).resolve()\n"
        "WORKSPACE_PATH = Path(WORKSPACE_DIR).resolve()\n"
        "ERROR_LOG_PATH = OUTPUT_PATH / 'error_log.txt'\n\n"
        "ensure_output_dir(OUTPUT_PATH)\n"
        "logger = NotebookLogger(ERROR_LOG_PATH)\n"
        "JAVA_ENV = configure_java_runtime(logger)\n"
        "JAVA_VERSION = java_version_text(JAVA_ENV)\n\n"
        "try:\n"
        "    REPO_PATH = resolve_repository_path(\n"
        "        use_git_repo=USE_GIT_REPO,\n"
        "        repo_url=REPO_URL,\n"
        "        local_repo=LOCAL_REPO,\n"
        "        workspace_dir=WORKSPACE_PATH,\n"
        "        if_clone_exists=IF_CLONE_EXISTS,\n"
        "        logger=logger,\n"
        "        clone_depth=CLONE_DEPTH,\n"
        "    )\n"
        "except Exception as exc:\n"
        "    logger.error(f'Repository setup failed: {exc}', step='repository')\n"
        "    raise\n\n"
        "BUILD_TOOL = detect_build_tool(REPO_PATH)\n"
        "JAVA_FILES = discover_java_files(REPO_PATH)\n"
        "if not JAVA_FILES:\n"
        "    logger.error('No Java source files found in repository.', step='discover')\n"
        "    raise FileNotFoundError('No Java source files found.')\n\n"
        "REPO_STATS = compute_repository_stats(REPO_PATH, JAVA_FILES, BUILD_TOOL, JAVA_VERSION)\n"
        "REPOSITORY_SUMMARY_CSV = OUTPUT_PATH / 'repository_summary.csv'\n"
        "pd.DataFrame([REPO_STATS]).to_csv(REPOSITORY_SUMMARY_CSV, index=False)\n\n"
        "print(f\"Repository Name: {REPO_STATS['repository_name']}\")\n"
        "print(f\"Repository Location: {REPO_STATS['repository_location']}\")\n"
        "print(f\"Build Tool: {REPO_STATS['build_tool']}\")\n"
        "print(f\"Java Version: {REPO_STATS['java_version']}\")\n"
        "print(f\"Total Java Files: {REPO_STATS['total_java_files']:,}\")\n"
        "print(f\"Repository Size (Java files): {REPO_STATS['repository_size_bytes']:,} bytes\")"
    ),
    md("## Section 5 — Discover Java Files"),
    code(
        "INVENTORY_CSV = OUTPUT_PATH / 'java_files_inventory.csv'\n"
        "save_java_inventory(JAVA_FILES, INVENTORY_CSV)\n\n"
        "print(f'Total Java Files Found: {len(JAVA_FILES)}')\n"
        "print(f'Saved inventory to: {INVENTORY_CSV}')\n"
        "display(pd.read_csv(INVENTORY_CSV).head())"
    ),
    md("## Section 6 — Detect Build Tool"),
    code(
        "print('Detected Build Tool:')\n"
        "print(BUILD_TOOL)\n"
        "if BUILD_TOOL == 'Maven':\n"
        "    print('Build command prefix:', ' '.join(resolve_maven_command(REPO_PATH, logger)))\n"
        "else:\n"
        "    print('Build command prefix:', ' '.join(resolve_gradle_command(REPO_PATH, logger)))"
    ),
    md("## Section 7 — Build Project"),
    code(
        "PIPELINE_STARTED = time.perf_counter()\n"
        "BUILD_STATUS, RAW_CONSOLE_OUTPUT = execute_build_and_jacoco(\n"
        "    REPO_PATH,\n"
        "    BUILD_TOOL,\n"
        "    JAVA_ENV,\n"
        "    logger,\n"
        ")\n"
        "TOTAL_EXECUTION_TIME = round(time.perf_counter() - PIPELINE_STARTED, 5)\n\n"
        "print(f'Build success: {BUILD_STATUS.build_success}')\n"
        "print(f'Test success: {BUILD_STATUS.test_success}')\n"
        "print(f'Report generated: {BUILD_STATUS.report_generated}')\n"
        "print(f'Execution time: {TOTAL_EXECUTION_TIME}s')"
    ),
    md("## Section 8 — Execute JaCoCo / Verify Reports"),
    code(
        "if BUILD_STATUS.report_dir:\n"
        "    print(f'JaCoCo report directory: {BUILD_STATUS.report_dir}')\n"
        "    for name, path in [\n"
        "        ('jacoco.exec', BUILD_STATUS.jacoco_exec),\n"
        "        ('jacoco.xml', BUILD_STATUS.jacoco_xml),\n"
        "        ('jacoco.csv', BUILD_STATUS.jacoco_csv),\n"
        "        ('index.html', BUILD_STATUS.index_html),\n"
        "    ]:\n"
        "        print(f\"  {name}: {'OK' if path and path.exists() else 'MISSING'} ({path})\")\n"
        "else:\n"
        "    logger.error('No JaCoCo report directory found.', step='jacoco')"
    ),
    md("## Section 9 — Raw Output Collection"),
    code(
        "CONSOLE_PATH = OUTPUT_PATH / 'jacoco_console_output.txt'\n"
        "CONSOLE_PATH.write_text(RAW_CONSOLE_OUTPUT, encoding='utf-8')\n"
        "logger.info(f'Saved raw console output to: {CONSOLE_PATH}')\n"
        "preview_raw_output(RAW_CONSOLE_OUTPUT, RAW_OUTPUT_PREVIEW_LINES, CONSOLE_PATH)"
    ),
    md("## Section 10 — Parse JaCoCo XML and Export Deliverables"),
    code(
        "if not BUILD_STATUS.report_generated:\n"
        "    raise FileNotFoundError('JaCoCo reports were not generated. See error_log.txt and jacoco_console_output.txt.')\n\n"
        "PARSED = collect_outputs(BUILD_STATUS, REPO_STATS, OUTPUT_PATH, TOTAL_EXECUTION_TIME, logger)\n"
        "METRICS_DF = PARSED['metrics_df']\n"
        "PACKAGE_DF = PARSED['package_df']\n"
        "CLASS_DF = PARSED['class_df']\n"
        "REPOSITORY_METRICS = PARSED['repository_metrics']\n\n"
        "display(METRICS_DF)\n"
        "display(PACKAGE_DF)\n"
        "display(CLASS_DF.head())"
    ),
    md("## Section 11 — Repository Summary"),
    code(
        "REPOSITORY_METRICS_CSV = OUTPUT_PATH / 'repository_metrics.csv'\n"
        "display(pd.read_csv(REPOSITORY_METRICS_CSV))"
    ),
    md("## Section 12 — Dashboard"),
    code(
        "dashboard_df = pd.DataFrame([\n"
        "    {'Metric': 'Repository', 'Value': REPO_STATS['repository_name']},\n"
        "    {'Metric': 'Build Tool', 'Value': REPO_STATS['build_tool']},\n"
        "    {'Metric': 'Java Files', 'Value': REPO_STATS['total_java_files']},\n"
        "    {'Metric': 'Packages', 'Value': REPOSITORY_METRICS['Total Packages']},\n"
        "    {'Metric': 'Classes', 'Value': REPOSITORY_METRICS['Total Classes']},\n"
        "    {'Metric': 'Instruction Coverage', 'Value': f\"{REPOSITORY_METRICS['Instruction Coverage %']}%\"},\n"
        "    {'Metric': 'Branch Coverage', 'Value': f\"{REPOSITORY_METRICS['Branch Coverage %']}%\"},\n"
        "    {'Metric': 'Line Coverage', 'Value': f\"{REPOSITORY_METRICS['Line Coverage %']}%\"},\n"
        "    {'Metric': 'Method Coverage', 'Value': f\"{REPOSITORY_METRICS['Method Coverage %']}%\"},\n"
        "    {'Metric': 'Class Coverage', 'Value': f\"{REPOSITORY_METRICS['Class Coverage %']}%\"},\n"
        "    {'Metric': 'Complexity Coverage', 'Value': f\"{REPOSITORY_METRICS['Complexity Coverage %']}%\"},\n"
        "])\n"
        "display(dashboard_df)\n\n"
        "deliverables = [\n"
        "    REPOSITORY_SUMMARY_CSV,\n"
        "    INVENTORY_CSV,\n"
        "    CONSOLE_PATH,\n"
        "    OUTPUT_PATH / 'jacoco.exec',\n"
        "    OUTPUT_PATH / 'jacoco.xml',\n"
        "    OUTPUT_PATH / 'jacoco.csv',\n"
        "    OUTPUT_PATH / 'index.html',\n"
        "    OUTPUT_PATH / 'jacoco_metrics.csv',\n"
        "    OUTPUT_PATH / 'package_summary.csv',\n"
        "    OUTPUT_PATH / 'class_summary.csv',\n"
        "    REPOSITORY_METRICS_CSV,\n"
        "    ERROR_LOG_PATH,\n"
        "]\n"
        "print('\\nDeliverables:')\n"
        "for path in deliverables:\n"
        "    print(f\"  [{'OK' if path.exists() else 'MISSING'}] {path}\")"
    ),
    md("## Section 13 — Error Handling"),
    code(
        "if ERROR_LOG_PATH.exists() and ERROR_LOG_PATH.stat().st_size > 0:\n"
        "    print(ERROR_LOG_PATH.read_text(encoding='utf-8'))\n"
        "else:\n"
        "    print('No errors logged.')"
    ),
    md(
        "## Deliverables\n\n"
        "```text\n"
        "outputs/\n"
        "├── repository_summary.csv\n"
        "├── java_files_inventory.csv\n"
        "├── jacoco_console_output.txt\n"
        "├── jacoco.exec\n"
        "├── jacoco.xml\n"
        "├── jacoco.csv\n"
        "├── index.html\n"
        "├── jacoco_metrics.csv\n"
        "├── package_summary.csv\n"
        "├── class_summary.csv\n"
        "├── repository_metrics.csv\n"
        "└── error_log.txt\n"
        "```"
    ),
]

NOTEBOOK.write_text(
    json.dumps(
        {
            "cells": cells,
            "metadata": {
                "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
                "language_info": {"name": "python", "version": "3.11.0"},
            },
            "nbformat": 4,
            "nbformat_minor": 5,
        },
        indent=1,
    ),
    encoding="utf-8",
)
print(f"Wrote {NOTEBOOK}")
