"""Generate static_du_extraction.ipynb."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
METRIC_ROOT = ROOT.parent
JACOCO_UTILS_ROOT = METRIC_ROOT.parent / "JaCoCo Coverage" / "tool"
NOTEBOOK = METRIC_ROOT / "static_du_extraction.ipynb"

BASE_UTILS = (JACOCO_UTILS_ROOT / "_jacoco_notebook_utils.py").read_text(encoding="utf-8")
STATIC_DU_UTILS = (ROOT / "_static_du_notebook_utils.py").read_text(encoding="utf-8")


def md(source: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": [line + "\n" for line in source.split("\n")]}


def code(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in source.split("\n")],
    }


cells = [
    md(
        "# Static DU — Raw Output Extraction (Java)\n\n"
        "This notebook performs **end-to-end execution of the Static DU (Definition-Use Analysis) tool** "
        "against a Java repository and captures the **complete raw tool output** without modifying "
        "or filtering the results.\n\n"
        "**Default repository:** "
        "[visvantha-testable/java-tool-testing-static-du]"
        "(https://github.com/visvantha-testable/java-tool-testing-static-du)\n\n"
        "> **Important:** Metrics are parsed only from explicit Static DU console and JSON outputs. "
        "Copied JSON files are preserved exactly as generated by the tool."
    ),
    md("## Section 1 — Install Dependencies"),
    code(
        "import platform\n"
        "import shutil\n"
        "import subprocess\n"
        "import sys\n\n"
        "IS_COLAB = 'google.colab' in sys.modules\n"
        "IS_LINUX = platform.system() == 'Linux'\n\n"
        "if IS_COLAB or IS_LINUX:\n"
        "    !apt-get update -qq\n"
        "    !apt-get install -y openjdk-17-jdk maven\n\n"
        "!pip install -q pandas gitpython notebook jupyter\n\n"
        "print('Java:')\n"
        "subprocess.run(['java', '-version'], check=False)\n"
        "if shutil.which('mvn'):\n"
        "    print('\\nMaven:')\n"
        "    subprocess.run(['mvn', '-version'], check=False)\n"
        "gradlew = shutil.which('gradlew')\n"
        "if gradlew:\n"
        "    print('\\nGradle wrapper found:', gradlew)"
    ),
    md("## Section 2 — Configuration"),
    code(
        "USE_GIT_REPO = True\n\n"
        "REPO_URL = 'https://github.com/visvantha-testable/java-tool-testing-static-du.git'\n\n"
        "LOCAL_REPO = './workspace/java-tool-testing-static-du'\n\n"
        "WORKSPACE_DIR = './workspace'\n"
        "OUTPUT_DIR = './outputs'\n"
        "IF_CLONE_EXISTS = 'reuse'\n"
        "CLONE_DEPTH = 1\n"
        "RAW_OUTPUT_PREVIEW_LINES = 150\n"
        "SKIP_VERIFY = True\n\n"
        "# Local mode example:\n"
        "# USE_GIT_REPO = False\n"
        "# LOCAL_REPO = './workspace/java-tool-testing-static-du'\n\n"
        "# Colab example:\n"
        "# USE_GIT_REPO = False\n"
        "# LOCAL_REPO = '/content/java-tool-testing-static-du'"
    ),
    md("## Section 3 — Imports and Utility Functions"),
    code(
        "import sys\n"
        "import time\n"
        "from pathlib import Path\n\n"
        "import pandas as pd\n"
        "from IPython.display import display\n\n"
        "JACOCO_UTILS_ROOT = Path('..') / 'JaCoCo Coverage' / 'tool'\n"
        "sys.path.insert(0, str(JACOCO_UTILS_ROOT.resolve()))\n"
        "sys.path.insert(0, str(Path('tool').resolve()))\n\n"
        + BASE_UTILS
        + "\n\n"
        + STATIC_DU_UTILS
    ),
    md("## Section 4 — Repository Information"),
    code(
        "OUTPUT_PATH = Path(OUTPUT_DIR).resolve()\n"
        "WORKSPACE_PATH = Path(WORKSPACE_DIR).resolve()\n"
        "ERROR_LOG_PATH = OUTPUT_PATH / 'error_log.txt'\n\n"
        "ensure_output_dir(OUTPUT_PATH)\n"
        "logger = NotebookLogger(ERROR_LOG_PATH)\n"
        "JAVA_ENV = configure_java_runtime(logger)\n"
        "JAVA_VERSION = java_version_text(JAVA_ENV)\n\n"
        "REPO_PATH = resolve_repository_path(\n"
        "    use_git_repo=USE_GIT_REPO,\n"
        "    repo_url=REPO_URL,\n"
        "    local_repo=LOCAL_REPO,\n"
        "    workspace_dir=WORKSPACE_PATH,\n"
        "    if_clone_exists=IF_CLONE_EXISTS,\n"
        "    logger=logger,\n"
        "    clone_depth=CLONE_DEPTH,\n"
        ")\n\n"
        "BUILD_TOOL = detect_build_tool(REPO_PATH)\n"
        "JAVA_FILES = discover_java_files(REPO_PATH)\n"
        "if not JAVA_FILES:\n"
        "    raise FileNotFoundError('No Java source files found.')\n\n"
        "REPO_STATS = compute_repository_stats(REPO_PATH, JAVA_FILES, BUILD_TOOL, JAVA_VERSION)\n"
        "REPOSITORY_SUMMARY_CSV = OUTPUT_PATH / 'repository_summary.csv'\n"
        "pd.DataFrame([REPO_STATS]).to_csv(REPOSITORY_SUMMARY_CSV, index=False)\n\n"
        "print(f\"Repository Name: {REPO_STATS['repository_name']}\")\n"
        "print(f\"Repository Path: {REPO_STATS['repository_location']}\")\n"
        "print(f\"Build Tool: {REPO_STATS['build_tool']}\")\n"
        "print(f\"Java Version: {REPO_STATS['java_version']}\")\n"
        "print(f\"Total Java Files: {REPO_STATS['total_java_files']}\")\n"
        "print(f\"Repository Size (bytes): {REPO_STATS['repository_size_bytes']}\")"
    ),
    md("## Section 5 — Discover Java Files"),
    code(
        "INVENTORY_CSV = OUTPUT_PATH / 'java_files_inventory.csv'\n"
        "save_java_inventory(JAVA_FILES, INVENTORY_CSV)\n"
        "display(pd.read_csv(INVENTORY_CSV).head(20))"
    ),
    md("## Section 6 — Detect Build Tool"),
    code(
        "print('Detected Build Tool:')\n"
        "print(BUILD_TOOL)\n"
        "platform = detect_static_du_platform(REPO_PATH)\n"
        "print('Static DU platform module:', platform)"
    ),
    md("## Section 7 — Build Project"),
    code(
        "PIPELINE_STARTED = time.perf_counter()\n"
        "STATIC_DU_STATUS, RAW_CONSOLE_OUTPUT = execute_static_du(\n"
        "    REPO_PATH,\n"
        "    JAVA_ENV,\n"
        "    logger,\n"
        "    skip_verify=SKIP_VERIFY,\n"
        ")\n"
        "print(f'Build success: {STATIC_DU_STATUS.build_success}')\n"
        "print(f'Static DU run success: {STATIC_DU_STATUS.run_success}')"
    ),
    md("## Section 8 — Execute Static DU Tool"),
    code(
        "if STATIC_DU_STATUS.command:\n"
        "    print('Static DU command:')\n"
        "    print(' '.join(STATIC_DU_STATUS.command))\n"
        "if STATIC_DU_STATUS.run_result:\n"
        "    print(f\"Execution time (s): {STATIC_DU_STATUS.run_result.execution_time_seconds}\")"
    ),
    md("## Section 9 — Preserve Raw Output"),
    code(
        "CONSOLE_PATH = OUTPUT_PATH / 'static_du_console_output.txt'\n"
        "CONSOLE_PATH.write_text(RAW_CONSOLE_OUTPUT, encoding='utf-8')\n"
        "COPIED = preserve_static_du_artifacts(STATIC_DU_STATUS, OUTPUT_PATH, REPO_PATH)\n"
        "print('Copied artifacts:', COPIED)\n"
        "preview_raw_output(RAW_CONSOLE_OUTPUT, RAW_OUTPUT_PREVIEW_LINES, CONSOLE_PATH)"
    ),
    md("## Section 10 — Extract Variable Definitions"),
    code(
        "TOTAL_EXECUTION_TIME = round(time.perf_counter() - PIPELINE_STARTED, 5)\n"
        "PARSED = collect_outputs(\n"
        "    STATIC_DU_STATUS,\n"
        "    REPO_PATH,\n"
        "    JAVA_FILES,\n"
        "    OUTPUT_PATH,\n"
        "    TOTAL_EXECUTION_TIME,\n"
        ")\n"
        "DEFINITIONS_DF = PARSED['definitions_df']\n"
        "if DEFINITIONS_DF.empty:\n"
        "    logger.error(\n"
        "        'Static DU did not emit per-definition records; only aggregate definition counts are present in JSON.',\n"
        "        step='parse_definitions',\n"
        "    )\n"
        "display(DEFINITIONS_DF.head(20))"
    ),
    md("## Section 11 — Extract Definition-Use Relationships"),
    code(
        "DU_PAIRS_DF = PARSED['du_pairs_df']\n"
        "display(DU_PAIRS_DF.head(20))"
    ),
    md("## Section 12 — Validate Required Metrics"),
    code(
        "DATA_FLOW_METRICS_DF = PARSED['metrics_df']\n"
        "display(DATA_FLOW_METRICS_DF)"
    ),
    md("## Section 13 — Repository Summary"),
    code(
        "REPOSITORY_METRICS_DF = PARSED['repository_metrics_df']\n"
        "display(REPOSITORY_METRICS_DF)"
    ),
    md("## Section 14 — Dashboard"),
    code(
        "DASHBOARD_DF = PARSED['dashboard_df']\n"
        "display(DASHBOARD_DF)"
    ),
    md("## Section 15 — Error Handling"),
    code(
        "logger.write_errors()\n"
        "if ERROR_LOG_PATH.exists():\n"
        "    display(pd.read_csv(ERROR_LOG_PATH))\n"
        "else:\n"
        "    print('No errors logged.')"
    ),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
            "pygments_lexer": "ipython3",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NOTEBOOK.write_text(json.dumps(notebook, indent=2), encoding="utf-8")
print(f"Wrote {NOTEBOOK}")
